### ISSUE TITLE
"Fork me on github" link only works with middle click on at least firefox

### ISSUE THREAD

**Issue by traverseda** [scopatz/xonsh-docs#1]

**Comment by scopatz** [comment]
Hmm that is not true for me. This works on firefox on linux with left click.

**Comment by traverseda** [comment]
https://www.youtube.com/watch?v=nMfJVj64QKU&feature=youtu.be

**Comment by scopatz** [comment]
Hmm very strange.  I am also on firefox 41.0.2 and using aweosme and I don't see this issue.  I don't see anything in the HTML or CSS that would indicate this type of behaviour. Thanks for reporting, but I am not sure what to do about it.

**Comment by traverseda** [comment]
Weird
